# Generated by Django 2.1.5 on 2019-04-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_votes',
        ),
    ]
